# Generated by Django 3.1.2 on 2020-12-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.CharField(default='Intro will come here', max_length=1000)),
                ('coverImage', models.ImageField(upload_to='images/')),
                ('sideImage', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Laf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=1000)),
                ('desc', models.CharField(default='description will come here', max_length=1000)),
                ('image', models.ImageField(upload_to='images/')),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=1000)),
                ('desc', models.CharField(default='description will come here', max_length=1000)),
                ('link', models.CharField(default='project_link', max_length=1000)),
                ('image', models.ImageField(upload_to='images/')),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=1000)),
                ('icon', models.ImageField(upload_to='images/')),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=1000)),
                ('desc', models.CharField(default='description will come here', max_length=1000)),
                ('year', models.CharField(default='year', max_length=1000)),
                ('rank', models.IntegerField()),
            ],
        ),
    ]
