# Generated by Django 3.1.2 on 2020-12-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='introduction',
            old_name='intro',
            new_name='para1',
        ),
        migrations.AddField(
            model_name='introduction',
            name='para2',
            field=models.CharField(default='Intro will come here', max_length=1000),
        ),
        migrations.AddField(
            model_name='introduction',
            name='para3',
            field=models.CharField(default='Intro will come here', max_length=1000),
        ),
        migrations.AddField(
            model_name='introduction',
            name='para4',
            field=models.CharField(default='Intro will come here', max_length=1000),
        ),
    ]
