# Generated by Django 3.1.2 on 2020-12-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201222_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='introduction',
            name='para5',
            field=models.CharField(default='Intro will come here', max_length=1000),
        ),
    ]
